AllCops:
  Include:
    - '**/metadata.rb'
    - '**/Gemfile'
    - attributes/**/*
    - definitions/**/*
    - libraries/**/*
    - providers/**/*
    - recipes/**/*
    - resources/**/*
    - test/**/*
  Exclude:
    - test/integration/data_bags/**/*

LineLength:
  Exclude:
    - attributes/**/*
    - test/**/*
